apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sportarr
  namespace: media
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Sportarr"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "sportarr.png"
    gethomepage.dev/description: "Sports automation"
    gethomepage.dev/href: "https://sportarr.home.arpa/"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sportarr.home.arpa
      secretName: homelab-wildcard-tls
  rules:
  - host: sportarr.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sportarr
            port:
              number: 1867
