apiVersion: v1
kind: Secret
metadata:
  name: homelab-ca-secret
  namespace: cert-manager
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    REPLACE_WITH_CA_CERT_PEM
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_CA_KEY_PEM
    -----END PRIVATE KEY-----
