apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  home.arpa.server: |
    home.arpa {
      hosts {
        192.168.1.18 qbittorrent.home.arpa
        192.168.1.18 sonarr.home.arpa
        192.168.1.18 radarr.home.arpa
        192.168.1.18 plex.home.arpa
        192.168.1.18 prowlarr.home.arpa
        192.168.1.18 sportarr.home.arpa
        192.168.1.18 homepage.home.arpa
        fallthrough
      }
      cache 30
    }
